export const atlpPaymentConstants = {
  PAYMENT_TOKEN_KEY: 'payment_token_key',
  PAYMENT_REFRESH_TOKEN_KEY: 'payment_refresh_token_key',
  MPAY_API_TIMEOUT: 90000,
  paymentRequestFields: {
    IsModalPayment: true,
    IsMobilePayment: false,
    UpdateStatusUrl: 'Maqta Url', // post api to update database to update payment
    CollectionType: 'Appointment Collection', // specific to application given by Mpay Team
    MerchantId: 'MGMERC00002', // sepcific to application given by Mapy Team
    TradeLicenseNumber: '00150230', // lba tradelicense value (UCID of the customer)
    GenerateOrderNo: false, // order no will be generated by mapy if true
    ApplyCharges: true,
    StdReceiptRequired: true, // receipot generated by mapay if true
    CreatedBy: 'MAQTA', // username of logged in user is mandatory (tokenisation) now not
    UserEmail: 'test@test.com', // not mandatory
    EnableEWalletCapture: true,
    ProductId: 'RETL',
    apiTransModel: {
      TransactionID: '01', // guid mandatory check
      TransactionNumber: '5491234', // check
      VATAmount: 0,
      VATRate: 0,
      RemainingAmount: 0,
      Rate: 100,
      Quantity: 1,
      Organization: 'MICCO', // ERP name of organization
      IsExternal: true, // check back
      InvoiceNumber: 'DERT6787656789', // depending upon on business logic
      RevenueAccountCode: 'NA',
      CategoryType: 'NA',
      CategoryValue: 'NA',
      Description: 'NA',
    },
    beneficiaryDetails: {
      // ERP and check with BA
      Organization: 'Abu Dhabi Port', // fixed
      TransactionID: '2354666',
      AccountCode: '9910214900501', // Fixed for Noqudi
    },
  },
};
